package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"hexa-example-go/internal/app/domain/in_ports"
)

// TodoLists is the resolver for the todoLists field.
func (r *queryResolver) TodoLists(ctx context.Context) ([]*TodoList, error) {
	panic(fmt.Errorf("not implemented: TodoLists - todoLists"))
}

// TodoListCreate is the resolver for the todoListCreate field.
func (r *queryResolver) TodoListCreate(ctx context.Context, name string) (*TodoList, error) {
	newTodoList, err := r.TodoListService.CreateTodoList(in_ports.CreateTodoListDTO{Name: name})

	// TODO: format error
	if err != nil {
		return nil, err
	}

	return &TodoList{
		ID:   newTodoList.Id,
		Name: newTodoList.Name,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
